app:
  port: 10002

mysql:
  host: 127.0.0.1
  port: 3306
  db: wallet-example
  user_name: root
  password: root
  max_idle_conn: 10
  max_open_conn: 256
  conn_max_life_time: 600

redis:
  addr: 127.0.0.1:6379
  password:
  db: 0

wallet:
  appid: 123123
  secret_key: 123123
  url: http://127.0.0.1:10001
  call_url: http://127.0.0.1:10002